### ISSUE TITLE
Ingress的路由和集群配置支持增量推送吗？

### ISSUE THREAD

**Issue by lizj3624** [alibaba/tengine-ingress#115]
比如：已有10个HTTP路由，每个路由关联一个backend，如果其中只有一个backend有变更，支持只推送这个变更的backend吗？

**Comment by lianglli** [comment]
支持的。每个Ingress可以指定对应的域名和Path，及其Upstream。

如果仅变更1个Ingress，那么tengine-ingress只会热加载这1个Ingress资源对象。
